# Generated by Django 3.0.8 on 2020-09-19 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_list_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='price',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Bid'),
        ),
    ]
