# Generated by Django 3.0.8 on 2020-09-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200929_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='list',
            new_name='lists',
        ),
    ]
