# Generated by Django 3.0.8 on 2020-10-06 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20201006_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
