# Generated by Django 3.0.8 on 2020-09-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200918_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='bid',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Bid'),
        ),
    ]
