# Generated by Django 3.0.8 on 2020-09-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_bid_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
