# Generated by Django 3.0.8 on 2020-09-18 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='title',
        ),
        migrations.AlterField(
            model_name='list',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Bid'),
        ),
    ]
