# Generated by Django 3.0.8 on 2020-09-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200918_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
