# Generated by Django 3.0.8 on 2020-09-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_list_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='price',
        ),
        migrations.AddField(
            model_name='bid',
            name='auclist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='auclists', to='auctions.List'),
        ),
        migrations.AddField(
            model_name='comment',
            name='auclist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.List'),
        ),
        migrations.AddField(
            model_name='list',
            name='noofbid',
            field=models.IntegerField(default=0),
        ),
    ]
