# Generated by Django 3.0.8 on 2020-10-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200929_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auclist',
        ),
        migrations.RemoveField(
            model_name='list',
            name='noofbid',
        ),
        migrations.AddField(
            model_name='bid',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='list',
            name='price',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Bid'),
        ),
    ]
